#!/bin/sh

set -o errexit
set -o nounset
set -o noclobber

name=nessel

# Re-run 3 times to get bibliographic changes through

#R --no-save --restore <<EOF
#Stangle("$name.Rnw")
#Sweave("$name.Rnw")
#EOF
pdflatex $name
bibtex $name
