#!/bin/sh

set -o errexit
set -o nounset
set -o noclobber

name=aps-poster

# Re-run 3 times to get bibliographic changes through

Rscript -e "library(knitr); knit('$name.Rnw')"
[ -d gen ] || mkdir gen
pdflatex $name
bibtex $name
