#!/bin/sh

#  germano1.csv

# obsolete:
#  earlydata/long-20130226.csv
#  earlydata/web-20120527.csv
#  earlydata/web-20120606.csv
#  earlydata/ppool-20121230.csv
# earlydata/web-20130105.csv
# earlydata/web-20130108.csv
# earlydata/short-20130215.csv
# earlydata/ppool-20130210.csv
# earlydata/ppool-20130213.csv
# earlydata/ppool-20130219.csv
# earlydata/short-20130219.csv
# earlydata/ppool-20130220.csv
# earlydata/long-20130221.csv

input='
  earlydata/grad-20130725.csv
  earlydata/short-20130725.csv
  yogaville/201309.csv
  earlydata/ppool-20130912.csv
  earlydata/short-20130912.csv
  earlydata/ppool-20131209.csv
  earlydata/short-20131221.csv'

# Don't add any more data to this file. See analyze2.R

sha1sum -c input.sha1

./sm2r $input raw.csv

# germano2013/import-germano2013 >> raw.csv
