#!/usr/bin/perl

use strict;
use warnings;
use Archive::Zip qw(AZ_OK);
use Text::CSV_XS;
use Fatal qw(open);
use Graph;
use Date::Manip;
use POSIX qw(strftime);
use Data::Dumper;
use IO::String;

my %ShortDict =
  ('mountainbiking' => 'mountain biking',
   'powerlifting' => 'weightlifting',
   'lifting' => 'weightlifting',
   'lifting weights' => 'weightlifting',
   'weight lifting' => 'weightlifting',
   'resistance training' => 'weightlifting',
   'strength training' => 'weightlifting',
   'weight training' => 'weightlifting',
   'softball' => 'baseball',
   'biking' => 'cycling',
   'bicycling' => 'cycling',
   'bike riding' => 'cycling',
   'jogging' => 'running',
   'zumba' => 'aerobic exercise',   # or dancing? TODO
   'playing soccer' => 'soccer',
   'horseback riding' => 'horseback riding',
   'refereeing high school basketball' => 'invalid',  # too many variations TODO
   'karate' => 'karate',
   'boxing' => 'boxing',
   'squash' => 'squash',
   'racquetball' => 'racquetball', # really different from squash? TODO
   'yoga' => 'hatha yoga',
   'gymnastics' => 'invalid',  # not specific enough
   'lacrosse' => 'lacrosse',
   'gym' => 'invalid',        # probably weights or running, but which?
   'circuit training' => 'weightlifting',
   'dodgeball' => 'dodgeball',
   'rugby' => 'rugby',
   'quidditch' => 'quidditch (sport)',
   'gym, jogging' => 'invalid',
   'run' => 'running',
   'swim' => 'swimming',
   'training' => 'invalid',
   'rugby union' => 'rugby',
   'lawn tennis' => 'tennis',
   'cross-fit' => 'invalid',
   'jiijoiojjio' => 'invalid',
   'inline skate' => 'inline skating',
  );

# 'Elliptical trainer' could be used for running or walking TODO
# split wrestling & jiu jitsu?

my %LongDict =
  (
   'basketball@indoor basketball' => 'basketball',
   'skiing@snow skiing' => 'snow skiing',
   'swimming@butterfly' => 'swimming',
   'weightlifting@i do a 6 day a week push-pull-leg routine (search up coolcicadas ppl for an idea of what i do), in the gym anytime from 45 minutes to an hour.' => 'weightlifting',
   'lifting@weight lifting' => 'weightlifting',
   'weight lifting@repeat, weight lifting' => 'weightlifting',
   'hockey@ice hockey goalie' => 'ice hockey',
   'body balance@it is mixture of yoga and pilates, but more dynamic and the exercises  have "choreographies" that fit with specific songs' => 'pilates',
   'golf@college golf' => 'golf',
   'baseball@college baseball' => 'baseball',
   'belly dancing@middle eastern dance. low impact' => 'dancing',  # dancing too large a category? TODO
   'bowling@10-pin style' => 'bowling',
   'baseball@college baseball' => 'baseball',
   'running@marathon and mini-marathon training' => 'running',
   'running@road running' => 'running',
   'running@running to get in shape' => 'running',
   'basketball@playing basketball 3 on 3' => 'basketball',
   'running@running on a track' => 'running',
   'golf@college golf' => 'golf',
   'baseball@college baseball' => 'baseball',
   'mma@mixed martial arts' => 'mixed martial arts',
   'football@american football' => 'football',
   'basketball@american basketball' => 'basketball',
   'walking@walking at a brisk pace through the neighborhood' => 'walking',
   'swimming@swimming at the beach and riding the waves' => 'swimming',
   'running@recreational running for the health and stress relief with the occasional race for fun' => 'running',
   'basketball@semi competitive club basketball on a college team' => 'basketball',
   'football@running and chasing after the running back' => 'football',
   'running@free running outside.' => 'running',
   'swimming@distance swimming' => 'swimming',
   'running@running on treadmill' => 'running',
   'running@running on a treadmill to burn fat' => 'running',
   'mma@mixed martial arts.'=> 'mixed martial arts',
   'football@intramural flag football' => 'football',
   'running@ran 1 mile.' => 'running',
   'ultimate frisbee@7 vs 7 frisbee on an approximate 50 yard field in college. 2-3x per week.' => 'ultimate frisbee',
   'soccer@intramural indoor soccer' => 'soccer',
   'soccer@advanced soccer, collegial elective course.' => 'soccer',
   'soccer@i play soccer with a group.' => 'soccer',
   'soccer@i play soccer when i am not dancing.' => 'soccer',
   'tennis@womens singles tennis' => 'tennis',
   'hiking@hiking in local park' => 'hiking',
   'tennis@singles' => 'tennis',
   'skiing@water skiing' => 'water skiing',
   'ping pong@also known as table tennis' => 'table tennis',
   'cricket@cricket- will answer questions in relation to bowling only' => 'cricket',
   'weight lifting@core and weight lifting to lean muscles' => 'weightlifting',
   'lifting@lifting weights' => 'weightlifting',
   'lifting@lifting weights to make my muscles stronger.' => 'weightlifting',
   'tennis@singles tennis' => 'tennis',
   'cycling@bike riding for exercise, sport, and transportation.' => 'cycling',
   'dance@hiphop dance' => 'dance',
   'dance@dance is what i rote and it is basically just hip hop dance!' => 'dance',
   'snowboarding@downhill snowboarding' => 'snowboarding',
   'vinyasa yoga@hot flow yoga' => 'hatha yoga',
   'hiit@high intensity interval training class at ymca (45-55 min)' => 'aerobic exercise',
   'track and field@shot-put and discus' => 'throwing sports',
   'netball@position- goal defence' => 'netball',
   'swimming@competitive lap swimming' => 'swimming',
   'running@running around a track' => 'running',
   'swimming@doing laps in a pool' => 'swimming',
   'running@running long distances of 1-2 miles or more' => 'running',
   'powerlifting@powerlifting is a sport that is based on your 1-rm.  in a competition setting, the athlete (myself) will have 3 chances to execute each one of the big lifts.  the big lifts are, squat, bench, and deadlift.  in a competition setting you will be judged for your performance and based on the rules if you succeed your score will be in the form of white lights.  a lifter must have 2 white lights out of the 3 for the attempt to count towards the final total you obtain at the end of the competition.' => 'weightlifting',
   'softball@high school' => 'baseball',
   'softball@i practice hitting and fielding' => 'baseball',
   'basketball@i run, dribble, and shoot basketballs' => 'basketball',
   'softball@hit and through softballs, ran, and had several workouts' => 'baseball',
   'basketball@ran, dribbled, and shot the basketballs' => 'basketball',
   'basketball@womens college basketball' => 'basketball',
   'basketball@college womens basketball' => 'basketball',
   'softball@church league softball' => 'baseball',
   'slow-pitch softball@slow-pitch softball is a recreational co-ed sport that i participate in.  generally you will have 4 out fielders and a regular infield set up, the pitcher will lob the ball for the batter to hit.  the game generally lasts an hour and 15 minutes depending on the league, and umpire is present to keep the game flowing smoothly.' => 'baseball',
   'swimming@swimming laps in a pool back and forth.' => 'swimming',
   'surfboard surfing@riding medium size (10) waves on the n shore and california' => 'surfing',
   'stand up paddle surfing@riding medium size (10) waves on the n shore and california but with less effort and risk than on a surfboard as standing minimizes take off risk' => 'stand up paddle surfing',
   'volleyball@hitting a ball back and forth over a net. avoiding it from touching the ground.' => 'volleyball',
   'springboard diving@1-meter and 3-meter springboard diving' => 'diving',
   'weight lifting@dumbbells' => 'weightlifting',
   'lifting@lifting weights in a gym setting' => 'weightlifting',
   'weight lifting@i do a variation of hang cleans, barbell squats, dead lifts, over-head snatchs, and any type of olympic lifts in sets that range from 5x5, 4x10, 5x3.' => 'weightlifting',
   'running@i run outside or on a treadmill usually 2 miles. or i elliptical for 30-45 min at moderate intensity.' => 'running',
   'tennis@tennis competitive, singles and doubles' => 'tennis',
   'basketball@social group with friends, not competitive' => 'basketball',
   'ice skating@2 hours session oft skating, together with some friends' => 'ice skating',
   'swimming@just swimming straight eines with a friend for 1.5 hours per week.' => 'swimming',
   'biking@riding my e-bike beyond the city limits' => 'cycling',
   'basketball@pickup basketball at the park' => 'basketball',
   'swimming@competitive swimming' => 'swimming',
   'basketball@varsity womens basketball' => 'basketball',
   'walking@i take long walks' => 'walking',
   'running@long distance running' => 'running',
   'swimming@swimming for cardio' => 'swimming',
   'gymnastics@medical gymnastics' => 'weightlifting',
   'gym@legs, abs and arm exercises' => 'weightlifting',
   'gym@i go to the gim to gain muscle mass. i train breast, legs, arms, neck and back.' => 'weightlifting',
   'trail running@running mostly on single-trails in the forest, with much incline' => 'running',
   'martial arts@wah lum kung fu' => 'Chinese martial arts',
   'swimming@lap swimming (freestyle), twice a week for roughly an hour each session.' => 'swimming',
   'ballet@i take beginner adult ballet classes, once a week' => 'ballet',
   'swimming@taking my kids to the swimming pool, diving, racing with them, playing basketball in the water, pulling and pushing them on floatation devices' => 'swimming',
   'walking@daily half hour walks outdoors in my town.' => 'walking',
   'football@flag football, outdoors.' => 'flag football',
   'marathon@walking a marathon, because of a drunken bet' => 'walking',
   'running@indoor running' => 'running',
   'volleyball@indoor volleyball' => 'volleyball',
   'zumba class@group exercise class' => 'aerobic exercise',
   'swimming@lap swimming, all four strokes plus drills and flip turns  - both for exercise and competition.' => 'swimming',
   'hiking@walking around, especially on natural trails' => 'hiking',
   'free weights@lifting weights not attached to a machine' => 'weightlifting',
   'skiing@resort skiing on trails, glades, and bowls in new england, va, and co.' => 'snow skiing',  # split from downhill? TODO
   'grappling@brazilian jiu jitsu and judo. although these are martial arts, they are more similar to to wrestling than boxing, karate, or tae kwon do.' => 'wrestling',
   'swimming walking@i would walk in the gym and for swimming i would just hang out with my friend in the' => 'invalid',
   'yuga@i would do stretch s' => 'hatha yoga',
   'strongman competition@strongman competitions include tests of strength and power including deadlift, clean and press, carrying, loading, pulling, and flipping. in contrast to powerlifting (squat, deadlift, bench press) or olympic weightlifting (snatch, clean and jerk) the events are not standardized across competitions.' => 'invalid',
   'soccer@organized outdoor 11 v 11 soccer' => 'soccer',
   'basketball@pick-up basketball' => 'basketball',
   'mountain biking@cross country mountain biking on mixed use and dedicated trails in the eastern coast states.  trail ratings of mainly blue and black.' => 'mountain biking',
   'treadmill@walking on a treadmill, at 3.7 speed, using rolling hills setting.' => 'walking',
   'running@running on the elliptical machine' => 'running',
   'elliptical@using an elliptical machine.' => 'running',
   'weightlifting@weightlifting using gym machine equipment (not free weights)' => 'weightlifting',
   'running@jogging and running daily' => 'running',
   'cardio fitness@cardio training with online videos at home' => 'aerobic exercise',
   'swimming@breaststroke' => 'swimming',
   'walking@walking up and down the hills' => 'walking',
   'cycling@cycling tours 50 to 80 miles' => 'cycling',
   'volleyball@mixed team volleyball' => 'volleyball',
   'jogging@outside' => 'running',
   'climbing@toprope, indoor climining walls' => 'rock climbing',
   'swimming@swimming while on holiday' => 'swimming',
   'yoga@stretches' => 'hatha yoga',
   'weight training@doing 7 days of workout of intensive weight training. for each day i assign a certain muscle group to focus on to ensure a good overall strength.' => 'weightlifting',
   'soccer@i played in a short 10 game season of recreational intramural soccer at my college.' => 'soccer',
   'swimming@in the open sea with my husband and dog for 30-40 minutes' => 'swimming',
   'walking@with my dog and often a friend in a variety of locations. usually for about 45 minutes.' => 'walking',
   'eliptical@ussage of eliptical' => 'running',
   'gym@lifting' => 'weightlifting',
   'aerobic@dancing' => 'aerobic exercise',
   'badminton@playing badminton with 3 others in a leisure center.' => 'badminton',
   'circuit training@on my own, in a gym, with a week long planned routine' => 'weightlifting',
   'kettle bell@work out with kettle bells' => 'weightlifting',
   'crunches@ab crunches' => 'weightlifting',
   'yoga@at home practice, primarily vinyasa style' => 'hatha yoga',
   'hiking@walking on trails in nature' => 'hiking',
   'field hockey@ncaa division i field hockey' => 'field hockey',
   'running@recreational running to keep in shape for sports, socialize with friends, and explore the area' => 'running',
   'weight lifting@lifting weights in a gym' => 'weightlifting',
   'hiking@hiking on nature trails/mountains' => 'hiking',
   'weight lifting@lifting weights' => 'weightlifting',
   'basketball@i played basketball on a outside court' => 'basketball',
   '5k running@running in one continuous interval a total of 5 kilometers or equivalently 3.1 miles.' => 'running',
   'resistance training@free weights lifting and core exercise.' => 'weightlifting',
   'running@casual jogging around city' => 'running',
   'playing soccer@playing soccer recreationally at university' => 'soccer',
   'roller derby@womens flat track roller derby' => 'roller derby',
   'martial arts@primarily jiu-jitsu, but also judo, kick boxing, wing chun, and wrestling' => 'mixed martial arts',
   'soccer@outdoor field soccer' => 'soccer',
   'weightlifting@lifting weights at a gym, not for competitive purposes' => 'weightlifting',
   'cycling@road biking on paved trails' => 'cycling',
   'golf@classic golf' => 'golf',
   'running@long distance' => 'running',
   'football@gaa' => 'football',
   'ultimate frisbee@pick-up ultimate frisbee, 6 on 6' => 'ultimate frisbee',
   'cycling@cycling to and from work (approximately 5 miles on regular roads, includes traffic signals and stop/start events 5-6 times in that distance)' => 'cycling',
   'swimming@lap swimming' => 'swimming',
   'elliptical@machine at the gym' => 'running',   # separate from running with separate category? TODO
   'speed walking@on high incline on treadmill' => 'running',
   'running@i run outside and enjoy participating in road races. i ran the richmond half marathon in november 2016.' => 'running',
   'swimming@i swim in an indoor pool for exercise.' => 'swimming',
   'recumbent elliptical@elliptical-style cardio machine with recumbent/semi-seated position. provides upper and lower body workout.' => 'running',
   'strength training@crunches and physical therapy exercises (lower body) with elastic band; upper body with kettlebells.' => 'weightlifting',
   'swimming@just recreational swimming' => 'swimming',
   'jogging@jogging for fun' => 'running',
   'swing dancing@lindy hop' => 'dancing',
   'zumba@salsa and bachata' => 'aerobic exercise',
   'racquetball@indoor' => 'racquetball',
   'basketball@pickup' => 'basketball',
   'running@running outside, not timed races or anything though' => 'running',
   'running@casual runs lasting from 2-5 miles, hill sprints up ohill observatory' => 'running',
   'wrestling@club wrestling' => 'wrestling',
   'swimming@competitive swimming on a team, including practices and meets' => 'swimming',
   'frisbee@pick-up ultimate frisbee' => 'ultimate frisbee',
   'weight lifting@lifting weights recreationally' => 'weightlifting',
   'running@jogging for exercise' => 'running',
   'rowing@rowing on the water and associated land training (erging)' => 'rowing',
   'running@regular individual runs of about 4 miles' => 'running',
   'yoga@vinyasa/ flow yoga' => 'hatha yoga',
   'running@i run ~11 minute miles for 1-3 miles at a time.' => 'running',
   'running@running outside on the street' => 'running',
   'gymnastics@competitive gymnastics such as they do in the  olympics' => 'invalid',
   'running@running on a treadmill at a constant speed for thirty minutes' => 'running',
   'hiking@walking on and off trails through the woods on small mountains' => 'hiking',
   'lacrosse@womens ncaa division 1 lacrosse' => 'lacrosse',
   'skateboarding@longboarding' => 'skateboarding',
   'horseback riding@eventing- dressage, stadium jumping, and cross country' => 'horseback riding',
   'running@long distance running- 10+ miles' => 'running',
   'basketball@5 v 5 full court' => 'basketball',
   'running@outdoors on streets' => 'running',
   'rock climbing@outdoor top roping, bouldering, and sport leading  indoor bouldering' => 'rock climbing',
   'running@recreational running around the town' => 'running',
   'hiking@hiked a mountain.' => 'hiking',
   'rock climbing@climbed at indoor rock wall.' => 'rock climbing',
   'strength training@lifting weights' => 'weightlifting',
   'yoga@vinyasa and ashtanga' => 'hatha yoga',
   'dance@lyrical' => 'dance',
   'strength training@lifting weights' => 'weightlifting',
   'yoga@vinyasa and ashtanga' => 'hatha yoga',
   'dance@lyrical' => 'dance',
   'stair stepper@stationary stair stepper machine at the gym' => 'running',
   'running@running on a treadmill inside at the gym' => 'running',
   'swimming@swimming laps' => 'swimming',
   'gymnastics@womens gymnastics' => 'invalid',
   'yoga@vinyasa yoga' => 'hatha yoga',
   'soccer@outdoor soccer; intramural, 8 v. 8' => 'soccer',
   'running@outdoor running' => 'running',
   'cycling@solo road cycling (not in a group of other riders)' => 'cycling',
   'weight training@strengthening muscles with free weights, barbell, and machines.' => 'weightlifting',
   'running@road running outside' => 'running',
   'swimming@lap swimming in a pool' => 'swimming',
   'running@running at an easy pace for 3-5 miles' => 'running',
   'soccer@american rules' => 'soccer',
   'yoga@heated power vinyasa' => 'hatha yoga',
   'weight lifting@lifting in a gym with both body weight and light weights' => 'weightlifting',
   'swimming@solo swimming - freestyle, breastroke' => 'swimming',
   'gym workout@rowing machine and free weights.' => 'invalid',
   'football@americans call it soccer but it should be called "football".' => 'soccer',
   'gymnastics@i compete in womens gymnastics' => 'invalid',
   'gymnastics@i compete in womens gymnastics.' => 'invalid',
   'running@5k-10k runs' => 'running',
   'circuit training' => 'weightlifting',
   'run@run on distance of approx. 10 km with a 5km per minute pace' => 'running',
   'football@playing outdoor football every sunday with buddies' => 'football',
   'walking@see above' => 'walking',
   'tibetian rites@see above' => 'invalid',  # too vague
   'bodyfit@muscle-building training' => 'weightlifting',
   'hockey@field' => 'field hockey',
   'walking@walking out in the woods.' => 'hiking',
   'cycling@ride my bycicle' => 'cycling',
   'circuit training' => 'weightlifting',
   '"running"' => 'running',
   'running@distance running' => 'running',
   'weight training@using weight machines in a gym' => 'weightlifting',
   'swimming@swimming laps and treading water' => 'swimming',
   'tai chi@beginner tai chi classes' => 'tai chi',
   'swimming@recreational lap swimming' => 'swimming',
   'dodgeball@national collegiate dodgeball association version of dodgeball.  1 hour long games.' => 'dodgeball',
   'running@regular jogging through streets.' => 'running',
   'baseball@american baseball' => 'baseball',
   'jumping@leaping up and down' => 'skipping rope',  # similar
   'running@jogging' => 'running',
   'rock climbing@mostly indoor, some outdoor, mostly bouldering, some top-rope, some competitions' => 'rock climbing',
   'volleyball@sand volleyball, non competitive' => 'volleyball',
   'kayaking@recreational solo kayaking on a sit on top kayak in a channel on the fraser river, and sometimes on the fraser river itself.' => 'kayaking',
   'walking@walking a trail in a treed area with a stream near my house.' => 'hiking',
   'swimming@swim laps of all 4 strokes' => 'swimming',
   'running@2-3 mile run' => 'running',
   'quidditch@we train twice a week.' => 'quidditch (sport)',
   'swimming@i train swimming about 3-4 times a week. we train for about 1.5h, swimming between 3.8 and 4.2km.' => 'swimming',
   'quidditch@collegiate quidditch is a club level sport at uva. it has been described as a combination of handball, dodgeball, and rugby.' => 'quidditch (sport)',
   'running@solo running, typically on a treadmill' => 'running',
   'ultimate frisbee@club ultimate frisbee team at uva' => 'ultimate frisbee',
   'gym@upper body workouts at a gym on uva grounds, usually with one or more other people' => 'weightlifting',
   'hiking@hiking on paths' => 'hiking',
   'rugby@rugby union - played with 15 players per team and 40 minute halves.' => 'rugby',
   'elliptical@using an elliptical at a gym' => 'running',
   'football@americans call it soccer but it should be called football.' => 'soccer',
   'body balance@it is mixture of yoga and pilates, but more dynamic and the exercises  have choreographies that fit with specific songs' => 'invalid',  # is this a thing?
   'swimming@swimming laps (crawl or breaststroke or eggbeater)' => 'swimming',
   'aerobic classes@high intensity interval training, insanity classes' => 'aerobic exercise',
   'swimming@i go swimming to do lanes once a week. i try to do 50 lanes' => 'swimming',
   'running@moving at a fast momentum. this can be done on a treadmill or outside. it can be done for fitness or competitively and at different distances.' => 'running',
   'yoga@vinyasa, hatha, flow,' => 'hatha yoga',
   'pilates@joseph method pilates' => 'pilates',
   'walking@i walk about a mile to and from my office every once in a while.' => 'walking',
   'bicycling@bicycling around the countryside, usually not more than ten miles.' => 'cycling',
   'track@sprinting' => 'running',
   'gym traiing@going to the gym and working out regularly' => 'invalid',
   'tennis@tennis where two people hit a ball over the net to each other' => 'tennis',
   'cycling@riding a bicycle in the nature' => 'cycling',
   'bouldering@climbing indoors with friends' => 'rock climbing',
   'dancing@dancing like dancing class as jazz dance' => 'dancing',
   'yoga@yoga, relaxing yoga' => 'hatha yoga',
   'biking@sometimes i mountain bike and other times i road bike. i usually go less than 10 miles. this year im just trying to do 5.6 miles a day and 410 vertical feet, road or mountain.' => 'cycling',
   'hiking@walking in nature.' => 'hiking',
   'hking@mountain hiking' => 'hiking',
   'gym@working out at the gym.' => 'invalid',
   'gym, jogging' => 'invalid',
   'dancing@zumba dancing' => 'dancing',
   'horseback riding@horseback riding in the english discipline' => 'horseback riding',
   'running@running outside on the track' => 'running',
   'swimming@any style of swimming' => 'swimming',
   'dancing@dancing at a party' => 'dancing',
   'basketball@5on5 full court basketball' => 'basketball',
   'weight training@-' => 'weightlifting',
   'snowboarding@-' => 'snowboarding',
   'running@running on a treadmill' => 'running',
   'soccer@soccer, the american kind.' => 'soccer',
   'football@football, not american footbal' => 'soccer',
   'running@going for a run' => 'running',
   'walking@going for a walk' => 'walking',
   'hiking@hiking in mountains' => 'hiking',
   'running@i usually run with my dogs, sometimes alone' => 'running',
   'yoga@assorted' => 'hatha yoga',
   'walking@45 minutes, twice daily' => 'walking',
   'gym@attending a variety of exercise machines' => 'invalid',
   'walkin@moving your body in a pace' => 'walking',
   'cycling@road cycling' => 'cycling',
   'gym activity@cardio or resistance training in a gym environment. on a range of equipment such as treadmill, elliptical or weight machines.' => 'invalid',
   'competitive swimming@competitive swimming to keep active, swimming can become repetitive and in competitive swimming it keep individuals motivated to aim for a goal.' => 'swimming',
   'skateboarding@street skateboarding' => 'skateboarding',
   'football@soccer' => 'soccer',
   'working out@working out such as lifting weights or cross fitting' => 'weightlifting',
   'softball@womens fastpitch softball' => 'baseball',
   'running@sprints' => 'running',
   'muay thai@muay thai is a thailand marcial art' => 'muay thai',
   'running@i usually run around 10 km at least three times a week, mainly on mornings. depending on the purpuse, i could run on streets or mountain roads (trail)' => 'running',
   'yoga@i do hatha yoga with an instructor once a week, at night.' => 'hatha yoga',
   'run@i run half marathons and i completed a full marathon on past october' => 'running',
   'swim@pool swimming' => 'swimming',
   'running@recreational running' => 'running',
   'training@weightlifting and cardio routines' => 'invalid',
   'karate@karate kyokushin and goju ryu' => 'karate',
   'strength training@lifting weights or using fitness machines' => 'weightlifting',
   'skiing@skiing down a mountain on alpine skis' => 'snow skiing',
   'strength training@intense workout in the gym, bodybuilding' => 'weightlifting',
   'hockey@field hockey' => 'field hockey',
   'gym@using weights, cardio' => 'invalid',
   'tennis@indoor tennis' => 'tennis',
   'hockey@ice hockey' => 'ice hockey',
   'gym@lifting weights, running, spinning, yoga' => 'invalid',
   'running@running in linger distances (marathon)' => 'running',
   'cycling@indoor spin class, road bikes' => 'cycling',
   'running@daily 5k' => 'running',
   'rock climbing@indoor and outdoor, bouldering, top rope, and sport climbing' => 'rock climbing',
   'ice skating@skating around on ice' => 'ice skating',
   'weight lifting@lifting weights and getting a pump' => 'weightlifting',
   'kayaking@long-distance river and open water >3 hrs at a time' => 'kayaking',
   'running@jogging in a park' => 'running',
   'tennis@singles and doubles at a moderate intensity' => 'tennis',
   'bike@mountain bike' => 'cycling',  # split into cycling and mountain biking? TODO
   'running@jogging 2-3 miles at a steady pace' => 'running',
   'basketball@playing 3 on 3 basketball on a half-court' => 'basketball',
   'cheerleading@competitive cheerleading' => 'cheerleading',
   'swimming@swimming in a pool, not outside' => 'swimming',
   'hiking@hiking with my dog, walking through the countryside .' => 'hiking',
   'football@gridiron football' => 'football',
   'weight lifting@lifting weights for all muscle areas of the body ,including squats, hammer curls, deadlifts, shoulder press, and so on.' => 'weightlifting',
   'running@running outside on the road/sidewalk' => 'running',
   'swimming@swimming in a regulation size pool indoors.' => 'swimming',
   'running@running as a form of cardio workout (mostly 12- 15km), sometimes i participate in half-marathons' => 'running',
   'running@ran distances between 1-4 miles at quick pace and sprints' => 'running',
   'tae bo@tae bo is a full body workout, combining martial arts, boxing, and elements of dance, set to fast pace music to form this intense cardio workout,' => 'aerobic exercise',
   'running@cross-country running' => 'running',
   'gym@running' => 'running',
   'rpm@classes at the gym' => 'aerobic exercise',  # or cycling? TODO
   'aerials (trapeze)@static trapeze and lyra' => 'trapeze',
   'inline skate@otherwise known as rollerblading  distance rollerblading' => 'inline skating',
   'tennis@i played tennis with my partner - we did not use a real court but we rallied the ball back and forth outside near our house on the concrete' => 'tennis',
   'football@it was not an official game but again more of a kick about outside with two of us' => 'soccer',
   'tennis@singles tennis match. best of 3 sets. causal but competitive game with a friend. 1.5 hours.' => 'tennis',
   'soccer@5 versus 5 soccer match lasting 2 hours.' => 'soccer',
   'badminton@singles and doubles badminton' => 'badminton',
   'yoga@yoga/pilates mix, yoga for runners, yoga for relaxing.' => 'hatha yoga',
   'running@short distance street running' => 'running',
   'swimming@swimming lengths in pool' => 'swimming',
   'running@10k road races' => 'running',
   'running@running 10k road and cross country races' => 'running',
   'cycling@cycling with family on road and off road' => 'cycling',
   'gym@weight lifting' => 'weightlifting',
   'running@just running...' => 'running',
   'yoga@yoga at studio and at home' => 'hatha yoga',
   'football@association football, i.e. soccer in usa' => 'soccer',
   'running@jogging, casual runs to maintain fitness' => 'running',
   'yoga@self practice at home' => 'hatha yoga',
   'walking@outdoor' => 'walking',
   'gym@<iron bars' => 'weightlifting',
   'running@casual jogging/running' => 'running',
   'swimming@solo lane swimming' => 'swimming',
   'walking@1.5 hour walk' => 'walking',
   'bike riding@1 hour push-bike ride' => 'cycling',
   'gym activity@cycling, treadmill and yoga stretching' => 'invalid',
   'skiing@alpine skiing' => 'snow skiing',
   'swimming@lane swimming' => 'swimming',
   'cross country@running' => 'running',
   'track@distance track' => 'running',
   'soccer@i play competitive soccer.' => 'soccer',
   'basketball@i play basketball for fun.' => 'basketball',
   'skiing@slide of mountains with snow.' => 'snow skiing',
   'running@go on the street and go faster than walking.' => 'running',
   'running@going for a run for 1-2 hours; outside' => 'running',
   'working out@circle training in the gym; mostly bodywight training; 1-3 circles and 6-9 exercises per circly' => 'weightlifting',
   'pilates@follow the teacher in a group on a pilates bed, all sorts of slow exact movements that you have to hold' => 'pilates',
   'swim@forward swimming stokes' => 'swimming',
   'power lifting@cleans, jerks, snatch' => 'weightlifting',
   'working out in the gym@light free weight exercises, cardio, machines, kettle bell' => 'invalid',
   'dancing@salsa' => 'dancing',
   'martial arts@karate' => 'karate',
   'poi@it is a juggling equipment, that involves 2 balls in the end of a string that you waving around yourself.' => 'poi (performance art)',
   'crosstraining@crosstrainer at home' => 'running',  # like eliptical
   'yoga@hatha yoga' => 'hatha yoga',
   'gymnastics@aerial silks' => 'aerial silk',
   'yoga@in class with a teacher, using yoga mats' => 'hatha yoga',
   'hiking@outside, with backpacks' => 'hiking',
   'yoga@hatha, nidra, balancing, breathing. piyo' => 'hatha yoga',
   'swimming@swimming pool: brass, back stroke' => 'swimming',
   'jijp@jjpjjojo' => 'invalid',
   'inline skate@otherwise known as rollerblading distance rollerblading' => 'inline skating',
   'rock climbing@outdoor top roping, bouldering, and sport leading indoor bouldering' => 'rock climbing',
   'working@gardening logging (cuting, woodwork) digging and builduing' => 'gardening',
   'martial arts@taekwondo - mostly kicking brazilian jiu jitsu - ground based grappling/submission wrestling mixed martial arts - mix of striking and grappling' => 'mixed martial arts',
   'wrestling@freestyle wrestling' => 'wrestling',
   'road hockey@road hockey is a variation on ice hockey during which an asphalt surface is used instead of ice. a hockey ball is used instead of a puck and running shoes are used instead of skates.' => 'road hockey',
  );

# Could remove some of these later when we have huge samples. TODO
my %GroupSoloOverride =
  ('aerobic exercise' => 'solo',
   tennis => 'group',
   'hatha yoga' => 'solo',
   walking => 'solo',
   running => 'solo',
   golf => 'group',
   basketball => 'group',
   weightlifting => 'solo',
   swimming => 'solo',
   cycling => 'solo',
   'brazilian jiu jitsu' => 'group',
   'horseback riding' => 'solo',  # the horse doesn't count
   'rock climbing' => 'solo',
   'hiking' => 'solo',
   'dance' => 'group',
   'soccer' => 'group',
   'dancing' => 'group',
   'snow skiing' => 'solo',
   'wrestling' => 'group',
  );

my %CountryMap =
  (
   'united states' => 'usa',
   'usa' => 'usa',
   'u.s.' => 'usa',
   'virginia' => 'usa',
   'canada' => 'canada',
   'germany' => 'germany',
   'uk' => 'united kingdom',
   'united kingdom' => 'united kingdom',
   'england' => 'united kingdom',
   'india' => 'india',
   'netherlands' => 'netherlands',
   'austria' => 'austria',
   'wales' => 'wales',
   'ireland' => 'ireland',
   'israel' => 'israel',
   'switzerland' => 'switzerland',
   'swiss' => 'switzerland',
   'australia' => 'australia',
   'costa rica' => 'costa rica',
   'brazil' => 'brazil',
   'portugal' => 'portugal',
   'sweden' => 'sweden',
  );

use constant RCPA_DEMOGRAPHICS => 9;
use constant PA1_START  => 15;
use constant PA2_START  => 18;
use constant RCPA_START => 21;

### BEGIN GLOBAL STATE

my %VettedName;
my %NodeInfo;
my %NodeGroupInfo;
my %EdgeInfo;
my $Graph = Graph::Undirected->new();

for my $k (values %LongDict) { $ShortDict{$k} = $k }
for my $k (values %ShortDict, values %LongDict) {
    die "Activity mapped to the empty string" if $k eq '';
    $VettedName{$k} = 1
}

### END GLOBAL STATE

sub trim {
    my ($str) = @_;
    $str =~ s/^\s+//;
    $str =~ s/\s+$//;
    $str
}

sub useNode {
    my ($pa,$solo) = @_;
    return if $pa eq 'invalid';
    if (exists $GroupSoloOverride{$pa}) {
	$solo = $GroupSoloOverride{$pa};
    }
    my $name = join(';', $pa, lc $solo);
    if (!exists $NodeInfo{$name}) {
	$NodeInfo{$name} = { count => 0 };
    }
    ++$NodeInfo{$name}{count};
    ++$NodeGroupInfo{$pa}{$solo};
    $name
}

sub node {
    my ($short, $long, $solo) = @_;
    $long = lc trim($long);
    $long =~ s/\"//g;
    $long =~ s/[\r\n]+/ /g;
    $short = lc trim($short);
    $short =~ s/\"//g;
    $short =~ s/\@//g;
    if ($long eq '' or $short eq $long) {
	if (exists $ShortDict{$short}) {
	    $short = $ShortDict{$short};
	    return useNode($short,$solo);
	} else {
	    print("   '$short' => '',\n");
	}
    } else {
	$long =~ s/\'//g;
	my $full = $short . '@' . $long;
	if (exists $LongDict{$full}) {
	    $short = $LongDict{$full};
	    return useNode($short,$solo);
	}
	if (exists $ShortDict{$short}) {
	    $short = $ShortDict{$short};
	}
	if (exists $VettedName{$short}) {
	    print "   '$full' => '$short',\n";
	} else {
	    print("   '$full' => '',\n");
	}
    }
    undef
}

our @RC_SKILL_MAP =
  ('{{Q9}} requires much more skill than {{Q6}}.',
   '{{Q9}} requires somewhat more skill than {{Q6}}.',
   'Both require roughly equal skill.',
   '{{Q6}} requires somewhat more skill than {{Q9}}.',
   '{{Q6}} requires much more skill than {{Q9}}.');

our @RC_PREDICT_MAP =
  ('{{Q6}} is much more predictable than {{Q9}}.',
   '{{Q6}} is somewhat more predictable than {{Q9}}.',
   'Both offer roughly equal predictability.',
   '{{Q9}} is somewhat more predictable than {{Q6}}.',
   '{{Q9}} is much more predictable than {{Q6}}.');

our @RC_NOVELTY_MAP =
  ('{{Q9}} offers a much more novelty than {{Q6}}.',
   '{{Q9}} offers a somewhat more novelty than {{Q6}}.',
   'Both offer roughly equal novelty.',
   '{{Q6}} offers a somewhat more novelty than {{Q9}}.',
   '{{Q6}} offers a much more novelty than {{Q9}}.');

our @RC_CREATIVE_MAP =
  ('{{Q6}} admits much more creativity than {{Q9}}.',
   '{{Q6}} admits somewhat more creativity than {{Q9}}.',
   'Both admit roughly the same amount of creativity.',
   '{{Q9}} admits somewhat more creativity than {{Q6}}.',
   '{{Q9}} admits much more creativity than {{Q6}}.');

our @RC_COMPLEX_MAP =
  ('{{Q9}} is much more complex than {{Q6}}.',
   '{{Q9}} is somewhat more complex than {{Q6}}.',
   'Both are of roughly equal complexity.',
   '{{Q6}} is somewhat more complex than {{Q9}}.',
   '{{Q6}} is much more complex than {{Q9}}.');

# Removed wording 'rules and' 2017 Jan 30 12:40pm
#
# Anonymous comment: The rules and goals question is double-barreled
# and should be separated. I didn't think running or weightlifting had
# "rules" and the goals can vary from strength to speed to weight
# loss. However I read that statement as inherent rules/goals (like
# football or other gaming sports) so I didn't answer that question
# for long or short-term. You may consider something like 'best
# practices' or techniques if that's what you're getting at.

our @RC_GOAL_MAP =
  ('{{Q6}} has much more clear goals than {{Q9}}.',
   '{{Q6}} has somewhat more clear goals than {{Q9}}.',
   'Both have equally clear goals.',
   '{{Q9}} has somewhat more clear goals than {{Q6}}.',
   '{{Q9}} has much more clear goals than {{Q6}}.');

our @RC_FEEDBACK_MAP =
  ('{{Q9}} has much more immediate feedback than {{Q6}}.',
   '{{Q9}} has somewhat more immediate feedback than {{Q6}}.',
   'Both offer roughly equally immediate feedback.',
   '{{Q6}} has somewhat more immediate feedback than {{Q9}}.',
   '{{Q6}} has much more immediate feedback than {{Q9}}.');

our @RC_CHATTER_MAP =
  ('{{Q6}} turns off my mental chatter much more than {{Q9}}.',
   '{{Q6}} turns off my mental chatter somewhat more than {{Q9}}.',
   'Both turn off my mental chatter to a roughly equal extent.',
   '{{Q9}} turns off my mental chatter somewhat more than {{Q6}}.',
   '{{Q9}} turns off my mental chatter much more than {{Q6}}.');

our @RC_WAITING_MAP =
  ('{{ Q9 }} involves a lot more waiting than {{ Q6 }}.',
   '{{ Q9}} involves a somewhat more waiting than {{ Q6}}.',
   'Both involve about the same amount of waiting.',
   '{{ Q6 }} involves a somewhat more waiting than {{ Q9}}.',
   '{{ Q6 }} involves a lot more waiting than {{ Q9}}.');

our @RC_BODY_MAP =
  ('{{Q6}} involves much more of my body than {{Q9}}.',
   '{{Q6}} involves somewhat more of my body than {{Q9}}.',
   'Both involve my body to a roughly equal extent.',
   '{{Q9}} involves somewhat more of my body than {{Q6}}.',
   '{{Q9}} involves much more of my body than {{Q6}}.');

our @RC_CONTROL_MAP =
  ('{{Q9}} permits much more control than {{Q6}}.',
   '{{Q9}} permits somewhat more control than {{Q6}}.',
   'Both admit roughly equal control.',
   '{{Q6}} permits somewhat more control than {{Q9}}.',
   '{{Q6}} permits much more control than {{Q9}}.');

our @RC_PRESENT_MAP =
  ('{{Q6}} brings me into the present much more than {{Q9}}.',
   '{{Q6}} brings me into the present somewhat more than {{Q9}}.',
   'Both bring me into the present to a roughly equal extent.',
   '{{Q9}} brings me into the present somewhat more than {{Q6}}.',
   '{{Q9}} brings me into the present much more than {{Q6}}.');

our @RC_SPONT_MAP =
  ('{{Q9}} feels effortless compare to {{Q6}} where I have to struggle and force myself.',
   '{{Q9}} feels like less effort than {{Q6}}.',
   'Both require about the same extent of effort (both either effortless or effortful).',
   '{{Q6}} feels like less effort than {{Q9}}.',
   '{{Q6}} feels effortless compare to {{Q9}} where I have to struggle and force myself.');

our @RC_STAKES_MAP =
  ('{{Q6}} has much higher stakes than {{Q9}}.',
   '{{Q6}} has somewhat higher stakes than {{Q9}}.',
   'Both have roughly equal stakes.',
   '{{Q9}} has somewhat higher stakes than {{Q6}}.',
   '{{Q9}} has much higher stakes than {{Q6}}.');

our @RC_EVALUATED_MAP =
  ("During {{Q9}}, I am much more concerned about others' evaluations than during {{Q6}}.",
   "During {{Q9}}, I am somewhat more concerned about others' evaluations than during {{Q6}}.",
   "During both {{Q9}} and {{Q6}}, I have roughly equal concern about others' evaluations.",
   "During {{Q6}}, I am somewhat more concerned about others' evaluations than during {{Q9}}.",
   "During {{Q6}}, I am much more concerned about others' evaluations than during {{Q9}}.");

our @RC_REWARD_MAP =
  ('{{Q6}} is much more rewarding than {{Q9}}.',
   '{{Q6}} is somewhat more rewarding than {{Q9}}.',
   'Both are roughly equally rewarding.',
   '{{Q9}} is somewhat more rewarding than {{Q6}}.',
   '{{Q9}} is much more rewarding than {{Q6}}.');

our @RC_INJURY1_MAP =
  ('{{Q9}} has much more chance of physical injury compare to {{Q6}}.',
   '{{Q9}} has somewhat more chance of physical injury compare to {{Q6}}.',
   'The chance of physical injury is roughly equal.',
   '{{Q6}} has somewhat more chance of physical injury compare to {{Q9}}.',
   '{{Q6}} has much more chance of physical injury compare to {{Q9}}.');

our @RC_INJURY2_MAP =
  ('{{Q6}} has much more chance of serious physical injury compare to {{Q9}}.',
   '{{Q6}} has somewhat more chance of serious physical injury compare to {{Q9}}.',
   'The chance of serious physical injury is roughly equal.',
   '{{Q9}} has somewhat more chance of serious physical injury compare to {{Q6}}.',
   '{{Q9}} has much more chance of serious physical injury compare to {{Q6}}.');

our @RC_MAP_SIGN;

sub cacheMapSign {
    my ($maps) = @_;
    return if scalar(@RC_MAP_SIGN);
    for my $map (@$maps) {
	$map->[0] =~ m/\{\{\s*Q(\d)\s*\}\}/;
	die $1 if ($1 != 6 and $1 != 9);
	my $sign = ($1 == 9)? -1 : 1;
	push @RC_MAP_SIGN, $sign;
    }
    die join('', @RC_MAP_SIGN) if join('', @RC_MAP_SIGN) ne '-11-11-11-11-11-11-11-11-11-11';
}

sub cmpToNum {
    my ($map, $cmp) = @_;
    return 'NA' if (!length $cmp);
    for my $x (0..4) {
	if ($map->[$x] eq $cmp) {
	    return ($x - 2)
	}
    }
    die "'$cmp' not found";
}

our %SHORT_MASTERY =
  ('Beginner' => 1,
   'Competent amateur' => 2,
   'Expert or professional' => 3);

sub shortenMastery {
    my ($mastery) = @_;
    my $sm = $SHORT_MASTERY{$mastery};
    die $mastery if !defined $sm;
    $sm;
}

sub edge {
    my ($n1, $l1, $n2, $l2, $version, $field, $recno) = @_;
    return if (!defined $n1 or !defined $n2);
    my @k = ($n1,$n2);
    my @sk = sort @k;
    my $sign = $k[0] ne $sk[0]? -1 : 1;
    my $k = join ':', @sk;
    if (!exists $EdgeInfo{$k}) {
	$EdgeInfo{$k} = { n1 => $sk[0], n2 => $sk[1], count => 0 };
    }
    my $info = $EdgeInfo{$k};
    $Graph->add_edge($k[0], $k[1]);
    my @m = (shortenMastery($l1), shortenMastery($l2));
    @m = reverse @m if $sign < 0;
    my @map = (\@RC_SKILL_MAP, \@RC_PREDICT_MAP, \@RC_NOVELTY_MAP, \@RC_CREATIVE_MAP,
	       \@RC_COMPLEX_MAP, \@RC_GOAL_MAP, \@RC_FEEDBACK_MAP, \@RC_GOAL_MAP, \@RC_FEEDBACK_MAP,
	       \@RC_CHATTER_MAP, \@RC_WAITING_MAP, \@RC_BODY_MAP, \@RC_CONTROL_MAP, \@RC_PRESENT_MAP,
	       \@RC_SPONT_MAP, \@RC_STAKES_MAP, \@RC_EVALUATED_MAP, \@RC_REWARD_MAP, \@RC_INJURY1_MAP,
	       \@RC_INJURY2_MAP);
    cacheMapSign(\@map);
    my $rating = [@m];
    for my $x (0..19) {
	my $got = cmpToNum($map[$x], $field->[RCPA_START + 4 + $x]);
#	if ($x == 1 and $recno == 174) { warn $got }
	if ($got ne 'NA') {
#	    if ($x == 1 and $recno == 174) { warn "$k order ".$sign }
#	    if ($x == 1 and $recno == 174) { warn "map ". $RC_MAP_SIGN[$x] }
	    $got *= $sign * $RC_MAP_SIGN[$x];
	    if ($x == 1 and Date_Cmp($version, "2016-12-25") < 0) {
		# switched from unpredict to predict
		$got *= -1;
#		if ($x == 1 and $recno == 174) { warn "flip old version" }
	    }
#	    if ($x == 1 and $recno == 174) { warn "-> $got" }
	}
	push @$rating, $got;
    }
    push @$rating, $recno;
    push @{ $info->{rating} }, $rating;
}

sub recordDemogr {
    my ($dfh, $csv, $di) = @_;
    my $country = lc(trim($di->[2]));
    if (length $country) {
	if (!exists $CountryMap{$country}) {
	    print "   '$country' => '$country',  # country\n";
	} else {
	    $di->[2] = $CountryMap{$country};
	}
    }
    $csv->say($dfh, $di);
}

sub loadZip {
    my ($zip) = @_;
    my $somezip = Archive::Zip->new();
    $somezip->read( $zip ) == AZ_OK or die $!;
    my $rawData = $somezip->contents('CSV/Relative characteristics of physical activities.csv');
    $rawData =~ tr/\xa0/ /;	# nonbreaking space
    $rawData =~ s/\xc2//gs;	# garbage?

    my $csv = Text::CSV_XS->new ({ keep_meta_info => 1, binary => 1 });
    open my $dfh, ">:encoding(utf8)", "demogr.csv";
    $csv->say($dfh, ['again', 'location', 'country', 'birthyear', 'edu', 'sex']);

    my $fh = IO::String->new($rawData);
    my $ignore_header1 = $csv->getline($fh);
    my $ignore_header2 = $csv->getline($fh);
    while (my $row = $csv->getline($fh)) {
	my @field = @$row;
	if (0) {
	    foreach my $col (0 .. $#field) {
		printf "%2d: %s\n", $col, $field[$col];
	    }
	}
	next if ($field[PA1_START] =~ m/^\s*$/ or $field[PA2_START] =~ m/^\s*$/);
	my $skipped = 0;
	for my $col (RCPA_START .. 42) {
	    ++$skipped if $field[$col] =~ /^\s*$/;
	}
	next if $skipped > 10;

	my $n1 = node($field[PA1_START], $field[PA1_START + 1], $field[RCPA_START+0]);
	my $n2 = node($field[PA2_START], $field[PA2_START + 1], $field[RCPA_START+1]);
	next if (!defined $n1 or !defined $n2 or $n1 eq $n2);
	my $l1 = $field[RCPA_START+2];
	my $l2 = $field[RCPA_START+3];
	next if ($l1 eq '' or $l2 eq '');
	edge($n1, $l1, $n2, $l2, ParseDate($field[2]), \@field, $csv->record_number());
	recordDemogr($dfh, $csv, [ @field[RCPA_DEMOGRAPHICS .. (RCPA_DEMOGRAPHICS+5)] ]);
    }
}

sub nodeColor {
    my ($code) = @_;
    if ($code == 1) { '#99cc33' }
    elsif ($code == 2) { '#cc9966' }
    else { '#993333' }
}

sub outputNode {
    my ($i, $id, $rate, $which) = @_;
    my $nk = 'n'.($which+1);
    my $name = simplifyName($i->{$nk});
    my @part = split /;/, $name;
    if (@part == 2) { $name = "$part[0] ($part[1])" }
    my $color = nodeColor($rate->[$which]);
    print "  {id: $id,  label: '$name', color: '$color' },\n";
}

sub outputGraph {
    open my $fh, ">", "pa-browser/rcpa-graph.js";
    my $oldOut = select $fh;

    my $stamp = strftime("%b %d, %Y", localtime());
    print "var RCPA_date = '$stamp';\n";

    my %NodeSet;

    my $NextId = 0;
    my %GNodeId;
    print "var RCPA_nodes = [\n";
    for my $k (sort keys %EdgeInfo) {
	my $i = $EdgeInfo{$k};
	for my $rate (@{$i->{rating}}) {
	    for my $which (0..1) {
		my $nk = 'n'.(1+$which);
		my $k1 = join ';', $i->{$nk}, $rate->[$which];
		if (!exists $GNodeId{$k1}) {
		    $GNodeId{$k1} = ++$NextId;
		    outputNode($i, $GNodeId{$k1}, $rate, $which);
		    if (!exists $NodeSet{ $i->{$nk} }) {
			$NodeSet{ $i->{$nk} } = [0,0,0];
		    }
		    my $rate1 = $rate->[2 + $which];
		    if ($rate1 ne 'NA') {
			$NodeSet{ $i->{$nk} }[ $rate1 ] = $GNodeId{$k1};
		    }
		}
	    }
	}
    }
    print "];\n";

    my %EdgeCount;
    for my $k (sort keys %EdgeInfo) {
	my $i = $EdgeInfo{$k};
	for my $rate (@{$i->{rating}}) {
	    my $k1 = join ';', $i->{n1}, $rate->[0];
	    my $k2 = join ';', $i->{n2}, $rate->[1];
	    ++$EdgeCount{"$k1--$k2"};
	}
    }

    print "var RCPA_edges = [\n";
    for my $k (sort keys %NodeSet) {
	my $set = $NodeSet{$k};
	for my $st (0..1) {
	    next if ($set->[$st] == 0 or $set->[$st+1] == 0);
	    print "  {from: $set->[$st], to: $set->[$st+1], color: { opacity: .5 }, dashes: true },\n";
	}
    }

    for my $k (sort keys %EdgeInfo) {
	my $i = $EdgeInfo{$k};
	for my $rate (@{$i->{rating}}) {
	    my $k1 = join ';', $i->{n1}, $rate->[0];
	    my $k2 = join ';', $i->{n2}, $rate->[1];
	    next if !exists $EdgeCount{"$k1--$k2"};
	    my $count = $EdgeCount{"$k1--$k2"};
	    print "  {from: $GNodeId{$k1}, to: $GNodeId{$k2}, value: $count },\n";
	    delete $EdgeCount{"$k1--$k2"}
	}
    }
    print "];\n";
    select $oldOut;
}

sub outputDebug {
    for my $k (sort keys %NodeInfo) {
	print "$k $NodeInfo{$k}{count}\n";
    }
    for my $k (sort keys %EdgeInfo) {
	print "$k $EdgeInfo{$k}{count}\n";
    }
}

sub simplifyName {
    my ($nn) = @_;
    my @part = split /;/, $nn;
    my $gi = $NodeGroupInfo{ $part[0] };
    if (keys %$gi == 1) {
	return $part[0]
    } else {
	return $nn;
    }
}

sub outputData {
    my $csv = Text::CSV_XS->new ({ binary => 1, auto_diag => 1 });
    open my $fh, ">:encoding(utf8)", "rawData.csv";
    $csv->say($fh, ['pa1', 'pa2', 'l1', 'l2', 'skill', 'predict', 'novelty', 'creative', 'complex',
		    'goal2', 'feedback2', 'goal1', 'feedback1', 'chatter', 'waiting',
		    'body', 'control', 'present', 'spont', 'stakes', 'evaluated', 'reward',
		    'injury1', 'injury2', 'recno']);
    my @cc = sort { $#$b <=> $#$a  } $Graph->connected_components();
    my %white;
    $white{$_}=1 for @{ $cc[0] };
    for my $edge (values %EdgeInfo) {
	next if (!$white{$edge->{n1}} or !$white{$edge->{n2}});
	for my $rate (@{ $edge->{rating} }) {
	    $csv->say($fh, [simplifyName($edge->{n1}), simplifyName($edge->{n2}), @$rate]);
	}
    }
}

loadZip(shift);

for my $k (keys %NodeGroupInfo) {
    my $gi = $NodeGroupInfo{$k};
    next if keys(%$gi) == 1;
    warn $k;  # to decide whether solo or group
}

outputGraph();

outputData();
