#!/bin/bash
#
#PBS -q serial
#PBS -N rcpa
#PBS -l ncpus=6
#

set -o errexit
set -o nounset
set -x

exec &> >(tee -a runStan.log)

date

git log -1 --oneline

R --no-save -f prepDemogr.R

for n in $(seq 7); do
  R --no-save -f f$n.R
done

# simulate data based on fit2t2
R --no-save -f sim5.R
R --no-save -f f8.R

R --no-save -f fitStats.R

R --no-save -f cluster.R
R --no-save -f threshplot.R
R --no-save -f thresholdCmp.R
R --no-save -f factorCmp.R
R --no-save -f checkSim.R
R --no-save -f genFlowData.R
R --no-save -f genWebResults.R

date
